theme = "ayu_evolve"

[keys.normal.space]
w = ":write"

[keys.normal]
w = "move_prev_word_start"
e = "move_next_word_start"
K = "page_cursor_half_up"
J = "page_cursor_half_down"
X = "extend_line_up"
D = "kill_to_line_end"
a = ["ensure_selections_forward", "collapse_selection", "move_char_right", "insert_mode"]
