theme = "ayu_evolve"

[keys.normal.space]
w = ":write"

[keys.normal]
e = "move_prev_word_start"
f = "move_next_word_start"
b = "move_next_word_end"
w = "find_next_char"
K = "page_cursor_half_up"
J = "page_cursor_half_down"
